import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { notoJP, playwriteQLD, gloria, baskervvilleSC } from "./fonts";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={[
          // keep Geist
          geistSans.variable,
          geistMono.variable,
          // add your custom fonts
          notoJP.variable,
          playwriteQLD.variable,
          gloria.variable,
          baskervvilleSC.variable,
          // default body + smoothing
          "font-sans antialiased",
        ].join(" ")}
      >
        {children}
      </body>
    </html>
  );
}
